version: '3.7'
networks:
  default:
    external:
      name: infra
services:
  sonarqube:
    image: "zebrunner/sonarqube:${TAG_SONAR}"
    image: "sonarqube:8.5-community"
    container_name: sonarqube
    # https://jira.sonarsource.com/browse/SONAR-13272 bug with SONAR_WEB_CONTEXT env variable
    command: -Dsonar.web.context=/sonarqube
    volumes:
      - ./plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.6.0.jar
      - ./plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.6.0.jar
      - "data-volume:/opt/sonarqube/data:rw"
      - "logs-volume:/opt/sonarqube/logs:rw"
      - "extensions-volume:/opt/sonarqube/extensions:rw"
    ports:
     - "9000:9000"
    restart: always
volumes:
  data-volume:
  logs-volume:
  extensions-volume:

