networks:
  default:
    name: infra
    external: true
services:
  sonarqube:
    image: "public.ecr.aws/zebrunner/sonarqube:${TAG_SONAR}"
    container_name: sonarqube
    # https://jira.sonarsource.com/browse/SONAR-13272 bug with SONAR_WEB_CONTEXT env variable
    command: -Dsonar.web.context=/sonarqube
    volumes:
      - "data-volume:/opt/sonarqube/data:rw"
      - "logs-volume:/opt/sonarqube/logs:rw"
      - "extensions-volume:/opt/sonarqube/extensions:rw"
    ports:
     - "9000:9000"
    restart: always
volumes:
  data-volume:
  logs-volume:
  extensions-volume:

